CREATE TABLE `computer_params` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `hash_id` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `os_full_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `bios_description` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `bios_manufacturer` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `bios_name` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `bios_release_date` varchar(25) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `bios_version` varchar(55) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `cpu_id` varchar(25) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `cpu_identifier` varchar(25) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `cpu_name` varchar(55) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `cpu_vendor` varchar(55) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `logical_cpu_count` varchar(2) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `physical_cpu_count` varchar(2) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `motherboard_manufacturer` varchar(55) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `motherboard_model` varchar(55) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `motherboard_serial` varchar(25) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `motherboard_version` varchar(25) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `disk_model` varchar(55) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `disk_name` varchar(55) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `disk_serial` varchar(25) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `disk_size` varchar(25) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `usb_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `usb_unique_device_id` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `usb_vendor` varchar(55) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `graphics_card_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `graphics_card_vendor` varchar(55) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `graphics_card_vram` varchar(25) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `memory_bank_label` varchar(25) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `memory_capacity` varchar(25) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `memory_manufacturer` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `memory_total` varchar(25) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `memory_type` varchar(25) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `adapters_names` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `ip_address` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `ip_mac_address` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `netbios_full_name` varchar(128) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    FOREIGN KEY (`hash_id`) REFERENCES computers (`hash_id`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
