CREATE TABLE `computer_params` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `computer_hash_id` bigint(20) NOT NULL,
    `os_full_name` varchar(255) NOT NULL DEFAULT '',
    `bios_description` varchar(255) NOT NULL DEFAULT '',
    `bios_manufacturer` varchar(255) NOT NULL DEFAULT '',
    `bios_name` varchar(100) NOT NULL DEFAULT '',
    `bios_release_date` varchar(25) NOT NULL DEFAULT '',
    `bios_version` varchar(55) NOT NULL DEFAULT '',
    `cpu_id` varchar(25) NOT NULL DEFAULT '',
    `cpu_identifier` varchar(25) NOT NULL DEFAULT '',
    `cpu_name` varchar(55) NOT NULL DEFAULT '',
    `cpu_vendor` varchar(55) NOT NULL DEFAULT '',
    `logical_cpu_count` int(2) NOT NULL DEFAULT 0,
    `physical_cpu_count` int(2) NOT NULL DEFAULT 0,
    `motherboard_manufacturer` varchar(55) NOT NULL DEFAULT '',
    `motherboard_model` varchar(55) NOT NULL DEFAULT '',
    `motherboard_serial` varchar(25) NOT NULL DEFAULT '',
    `motherboard_version` varchar(25) NOT NULL DEFAULT '',
    `disk_model` varchar(55) NOT NULL DEFAULT '',
    `disk_name` varchar(55) NOT NULL DEFAULT '',
    `disk_serial` varchar(25) NOT NULL DEFAULT '',
    `disk_size` bigint(20) NOT NULL DEFAULT 0,
    `usb_name` varchar(255) NOT NULL DEFAULT '',
    `usb_unique_device_id` varchar(255) NOT NULL DEFAULT '',
    `usb_vendor` varchar(55) NOT NULL DEFAULT '',
    `graphics_card_name` varchar(255) NOT NULL DEFAULT '',
    `graphics_card_vendor` varchar(55) NOT NULL DEFAULT '',
    `graphics_card_vram` bigint(20) NOT NULL DEFAULT 0,
    `memory_bank_label` varchar(25) NOT NULL DEFAULT '',
    `memory_capacity` bigint(20) NOT NULL DEFAULT 0,
    `memory_manufacturer` varchar(255) NOT NULL DEFAULT '',
    `memory_total` bigint(20) NOT NULL DEFAULT 0,
    `memory_type` varchar(25) NOT NULL DEFAULT '',
    `adapters_names` varchar(255) NOT NULL DEFAULT '',
    `ip_address` varchar(255) NOT NULL DEFAULT '',
    `mac_address` varchar(255) NOT NULL DEFAULT '',
    `netbios_full_name` varchar(128) NOT NULL DEFAULT '',
    PRIMARY KEY `id` (`id`),
    CONSTRAINT `hash_id_ibfk_1`
    FOREIGN KEY (computer_hash_id)
    REFERENCES computers (computer_hash_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
